### ISSUE TITLE
ScoreHud does not update money

### ISSUE THREAD

**Issue by MrBlasyMSK** [cooldogedev/BedrockEconomy#67]
**Describe the bug**
When you add money to a player, the scorehud is updated for 1 millisecond to the money you have added, but after a second it disappears and returns to the money you had before.

**To Reproduce**
https://streamable.com/43poru

**Expected behavior**
ScoreHud will be updated correctly when adding or removing money.

**Screenshots**
Video up

**OS and version (please complete the following information):**
 - Server OS: linux
 - PocketMine-MP version: 4.2.4
 - Version: 2.0.7
 - Plugins (2): BedrockEconomy v2.0.7, ScoreHud v7.0.0

**Additional context**
X

**Comment by cooldogedev** [comment]
This could be happening due to a race conflict in https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/addon/scorehud/ScoreHudListener.php#L92-#L107

**Comment by MrBlasyMSK** [comment]
> This could be happening due to a race conflict in https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/addon/scorehud/ScoreHudListener.php#L92-#L107

Is there any way to correct that?

**Comment by cooldogedev** [comment]
I already have a solution for this issue, I'll look into it tomorrow.

**Comment by cooldogedev** [comment]
I can't reproduce this

**Comment by cooldogedev** [comment]
Can you provide your configuration file (without the mysql credentials)

**Comment by MrBlasyMSK** [comment]
```yaml
---
# Configuration version, don't edit this.
config-version: 2.0.7

language: es-ES

utility:
  # The numbers of accounts to display when using the command.
  top-balance-accounts-limit: 10

currency:
  # The name of the currency.
  name: EUR
  # The symbol of the currency.
  symbol: €

  balance:
    # The balance for new users.
    default-balance: 1000
    # This has no effect if `enable-balance-cap` is false.
    balance-cap: 100000
    # Enabling this will disallow users from exceeding the balance cap.
    enable-balance-cap: false

  payment:
    # The minimum amount of money a user can send.
    minimum-payment: 100
    # The maximum amount of money a user can send.
    maximum-payment: 1000000

database:
  # The database provider, mysql or sqlite.
  provider: sqlite
  # Number of threads to use for the database query processing, 2 is recommended.
  threads: 2
  ```

**Comment by cooldogedev** [comment]
Can you try using the latest poggit build?

**Comment by MrBlasyMSK** [comment]
```
PocketMine-MP Crash Dump Sun Mar 20 16:02:07 UTC 2022

Error: Undefined array key "number-separator"
File: plugins/BedrockEconomy_dev-26.phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager
Line: 52
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedrockEconomy

Code:

Backtrace:
#0 plugins/BedrockEconomy_dev-26.phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager(52): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[38] Undefined array key "number-separator", string[117] phar:///home/container/plugins/BedrockEconomy_dev-26.phar/src/cooldogedev/Bedroc, integer 52)
#1 plugins/BedrockEconomy_dev-26.phar/src/cooldogedev/BedrockEconomy/BedrockEconomy(104): cooldogedev\BedrockEconomy\currency\CurrencyManager->__construct(object cooldogedev\BedrockEconomy\BedrockEconomy#110974)
#2 pmsrc/src/plugin/PluginBase(137): cooldogedev\BedrockEconomy\BedrockEconomy->onEnable()
#3 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#4 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object cooldogedev\BedrockEconomy\BedrockEconomy#110974)
#5 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901)
#6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#7 pmsrc/src/PocketMine(327): pocketmine\server()
#8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

PocketMine-MP version: 4.2.4 [Protocol 486]
Git commit: 05a5e5eac126064583af2e892cb9b3cc0b0a88b6
uname -a: Linux 40988d2c-8e2a-4b5a-ab32-2bc6e7d3056e 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
PHP Version: 8.0.16
Zend version: 4.0.16
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
- pocketmine/bedrock-protocol 8.0.1+bedrock-1.18.10@a740f6095b35278c0e0dac6db84a5e4d2456b113
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.2.4@05a5e5eac126064583af2e892cb9b3cc0b0a88b6
- pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.25.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php80 v1.25.0@4407588e0d3f1f52efb65fbe92babe41f37fe50c
- symfony/polyfill-php81 v1.25.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725
```

**Comment by cooldogedev** [comment]
your configuration file is outdated, try this one.

```yaml
---
# Configuration version, don't edit this.
config-version: 2.0.7

language: es-ES

utility:
  # The numbers of accounts to display when using the command.
  top-balance-accounts-limit: 10

currency:
  # The name of the currency.
  name: EUR
  # The symbol of the currency.
  symbol: €
  number-separator: ","

  balance:
    # The balance for new users.
    default-balance: 1000
    # This has no effect if `enable-balance-cap` is false.
    balance-cap: 100000
    # Enabling this will disallow users from exceeding the balance cap.
    enable-balance-cap: false

  payment:
    # The minimum amount of money a user can send.
    minimum-payment: 100
    # The maximum amount of money a user can send.
    maximum-payment: 1000000

database:
  # The database provider, mysql or sqlite.
  provider: sqlite
  # Number of threads to use for the database query processing, 2 is recommended.
  threads: 2
```

**Comment by MrBlasyMSK** [comment]
If u fix that first i can try it
```
PocketMine-MP Crash Dump Mon Mar 21 12:16:28 UTC 2022

Error: Undefined array key "number-separator"
File: plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager
Line: 52
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedrockEconomy

Code:

Backtrace:
#0 plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager(52): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[38] Undefined array key "number-separator", string[121] phar:///home/container/plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/Be, integer 52)
#1 plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/BedrockEconomy(104): cooldogedev\BedrockEconomy\currency\CurrencyManager->__construct(object cooldogedev\BedrockEconomy\BedrockEconomy#28273)
#2 pmsrc/src/plugin/PluginBase(137): cooldogedev\BedrockEconomy\BedrockEconomy->onEnable()
#3 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#4 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object cooldogedev\BedrockEconomy\BedrockEconomy#28273)
#5 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901)
#6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#7 pmsrc/src/PocketMine(327): pocketmine\server()
#8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

PocketMine-MP version: 4.2.4 [Protocol 486]
Git commit: 05a5e5eac126064583af2e892cb9b3cc0b0a88b6
uname -a: Linux 40988d2c-8e2a-4b5a-ab32-2bc6e7d3056e 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
PHP Version: 8.0.16
Zend version: 4.0.16
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
- pocketmine/bedrock-protocol 8.0.1+bedrock-1.18.10@a740f6095b35278c0e0dac6db84a5e4d2456b113
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.2.4@05a5e5eac126064583af2e892cb9b3cc0b0a88b6
- pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.25.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php80 v1.25.0@4407588e0d3f1f52efb65fbe92babe41f37fe50c
- symfony/polyfill-php81 v1.25.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725
```

**Comment by cooldogedev** [comment]
> If u fix that first i can try it
> 
> ```
> PocketMine-MP Crash Dump Mon Mar 21 12:16:28 UTC 2022
> 
> Error: Undefined array key "number-separator"
> File: plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager
> Line: 52
> Type: ErrorException
> 
> THIS CRASH WAS CAUSED BY A PLUGIN
> BAD PLUGIN: BedrockEconomy
> 
> Code:
> 
> Backtrace:
> #0 plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/currency/CurrencyManager(52): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[38] Undefined array key "number-separator", string[121] phar:///home/container/plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/Be, integer 52)
> #1 plugins/BedrockEconomy_dev-26 (1).phar/src/cooldogedev/BedrockEconomy/BedrockEconomy(104): cooldogedev\BedrockEconomy\currency\CurrencyManager->__construct(object cooldogedev\BedrockEconomy\BedrockEconomy#28273)
> #2 pmsrc/src/plugin/PluginBase(137): cooldogedev\BedrockEconomy\BedrockEconomy->onEnable()
> #3 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
> #4 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object cooldogedev\BedrockEconomy\BedrockEconomy#28273)
> #5 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24901)
> #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
> #7 pmsrc/src/PocketMine(327): pocketmine\server()
> #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
> 
> PocketMine-MP version: 4.2.4 [Protocol 486]
> Git commit: 05a5e5eac126064583af2e892cb9b3cc0b0a88b6
> uname -a: Linux 40988d2c-8e2a-4b5a-ab32-2bc6e7d3056e 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
> PHP Version: 8.0.16
> Zend version: 4.0.16
> OS: Linux, linux
> Composer libraries: 
> - adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
> - brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
> - daverandom/callback-validator unknown@unknown
> - fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
> - netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
> - pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
> - pocketmine/bedrock-protocol 8.0.1+bedrock-1.18.10@a740f6095b35278c0e0dac6db84a5e4d2456b113
> - pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
> - pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
> - pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
> - pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
> - pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
> - pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
> - pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
> - pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
> - pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
> - pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
> - pocketmine/pocketmine-mp 4.2.4@05a5e5eac126064583af2e892cb9b3cc0b0a88b6
> - pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
> - pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
> - pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
> - ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
> - ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
> - rhumsaa/uuid unknown@unknown
> - symfony/polyfill-ctype v1.25.0@30885182c981ab175d4d034db0f6f469898070ab
> - symfony/polyfill-php80 v1.25.0@4407588e0d3f1f52efb65fbe92babe41f37fe50c
> - symfony/polyfill-php81 v1.25.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
> - webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
> - webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725
> ```

This isn't a bug, it's an outdated configuration file, there is a new configuration line that you don't have in your configuration file.

**Comment by cooldogedev** [comment]
delete your existing configuration file and wait for the plugin to generate a new one, or use the one i sent above.

**Comment by MrBlasyMSK** [comment]
> onfiguration file and wait for the plugin to generate a new one, or use the one i sent above

oh ok, i will try

**Comment by MrBlasyMSK** [comment]
Dinero: N/A means Money: N/A

![imagen_2022-03-21_133255](https://user-images.githubusercontent.com/85447029/159261863-73671293-31b2-4752-9b2b-3e79052041f0.png)
This is what I got when I logged in for the first time without a BedrockEconomy database.

![imagen_2022-03-21_133540(1)](https://user-images.githubusercontent.com/85447029/159262191-50e84b89-3adf-4ae2-b912-3f6ff41b0c0f.png)
This is what I get if I log out and log in

And I tried to use /addbalance MrBlasyMSK 100 but it didn't update ScoreHud, only for 1 millisecond.

**Comment by cooldogedev** [comment]
are you using mysql?

**Comment by MrBlasyMSK** [comment]
> are you using mysql?

```yml
database:
  # The database provider, mysql or sqlite.
  provider: sqlite
  # Number of threads to use for the database query processing, 2 is recommended.
  threads: 2
  ```

**Comment by cooldogedev** [comment]
I've been trying to reproduce this but never got it to work.

**Comment by MrBlasyMSK** [comment]
> I've been trying to reproduce this but never got it to work.

Maybe you need to put the tick update in scorehud to 1, it's how I have it

**Comment by MrBlasyMSK** [comment]
Like this
```yml
---
# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
scorehud-version: 3

# Set the title for the scoreboard shown.
titles:
  # If *true* then 'titles.lines' will be used for showing changing
  # or flickering titles. Although fancy but they might cause lag
  # so be your own judge. This may also cause the scoreboard to
  # flicker at times. (not preferred)
  #
  # If *false* then 'titles.title' will be used for showing a simple
  # title on the scoreboard. (preferred)
  flicker: true

  # If 'titles.flicker' is set to true then adjust the rate at which
  # the titles should change. In seconds.
  # Default: 5 (seconds)
  period: 1
  ```
